import {
    VerticalBox,
    HorizontalBox,
    Switch,
    Palette,
} from "std-widgets.slint";

export component AppWindow inherits Window {
    icon: @image-url("../assets/icon.svg");
    title: "WCH-Next";
    width: 320px;
    height: 180px;

    in property <bool> acw-status: true;
    in property <bool> autorun-status: false;
    in property <string> active-app: "未检测到应用程序";
    callback auto-center-window(bool);
    callback set_autorun(bool);

    VerticalBox {
        padding: 16px;
        spacing: 16px;

        // 自动居中开关
        HorizontalBox {
            spacing: 8px;

            Text {
                text: "自动居中";
                color: Palette.foreground.transparentize(0.4);
                font-size: 13px;
                vertical-alignment: center;
            }

            Rectangle { }

            Switch {
                checked: root.acw-status;
                toggled => {
                    auto-center-window(self.checked);
                }
            }
        }

        // 自动启动开关
        HorizontalBox {
            spacing: 8px;

            Text {
                text: "自动启动";
                color: Palette.foreground.transparentize(0.4);
                font-size: 13px;
                vertical-alignment: center;
            }

            Rectangle { }

            Switch {
                checked: root.autorun-status;
                toggled => {
                    set_autorun(self.checked);
                }
            }
        }

        // 当前活动应用
        HorizontalBox {
            spacing: 8px;

            Text {
                text: "当前应用";
                color: Palette.foreground.transparentize(0.4);
                font-size: 13px;
                vertical-alignment: center;
            }

            Rectangle { }

            Text {
                text: active-app;
                color: Palette.foreground;
                font-size: 13px;
                font-weight: 600;
                overflow: elide;
                vertical-alignment: center;
                horizontal-alignment: right;
            }
        }
    }
}

export component TrayIcon inherits SystemTrayIcon {
    icon: @image-url("../assets/icon.svg");
    tooltip: "WCH-Next";

    callback show-window();
    callback hide-window();
    callback quit-program();

    Menu {
        MenuItem {
            title: "Show";
            activated => { show-window(); }
        }

        MenuItem {
            title: "Hide";
            activated => { hide-window(); }
        }

        MenuItem {
            title: "Quit";
            activated => { quit-program(); }
        }
    }
}
